# -*- coding: utf-8 -*-
"""КП6_Данильчук_DA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_RnChX98KGXTUagux12SGJ32pPoYfPOn

1. Завантаження даних

Row,Order, Customer and Product ID\
Order and Ship Date\
Ship Mode\
Customer Name\
Segment\
City, State, Region, Country, Postal Code\
Market\
Category, Sub-Category\
Product Name\
Sales\
Quantity\
Discount\
Profit\
Shipping Cost\
Order Priority
"""
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import altair as alt
import numpy as np
import plotly.express as px
from sklearn.linear_model import LinearRegression
from sklearn.cluster import KMeans

df = pd.read_csv('Global_Superstore2.csv', encoding='latin-1')

df.info()
df.describe()

#Конфігурація
st.set_page_config(
    page_title="Perfomance dashboard",
    page_icon="📈📋",
    layout="wide",
    initial_sidebar_state="collapsed",
    menu_items={
        'Get Help': 'https://docs.streamlit.io/',
        'Report a bug': 'https://github.com/streamlit/streamlit/issues',
        'About': 'Інформаційна панель для аналізу діяльності компанії'
    }
)

#Sidebar
st.sidebar.title("Фільтри")
df["Order Date"] = pd.to_datetime(df["Order Date"])

#Creating year column
df["Year"] = df["Order Date"].dt.year
selected_year = st.sidebar.selectbox("Рік",sorted(df["Year"].unique()))

selected_segment = st.sidebar.multiselect("Сегмент", df["Segment"].unique(), default=df["Segment"].unique())

selected_category = st.sidebar.multiselect("Категорія продукту", df["Category"].unique(), default=df["Category"].unique())

selected_subcategory = st.sidebar.multiselect("Підкатегорія", df["Sub-Category"].unique(), default=df["Sub-Category"].unique())

selected_country = st.sidebar.multiselect("Країна", df["Country"].unique(), default=df["Country"].unique())

selected_market = st.sidebar.multiselect("Ринок", df["Market"].unique(), default=df["Market"].unique())

selected_priority = st.sidebar.radio("Рівень пріоритету", df["Order Priority"].unique())

selected_shipment = st.sidebar.radio("Доставка", df["Ship Mode"].unique())

selected_maxqn = st.sidebar.slider(
    "Максимальна кількість замовлення",
    min_value=int(df["Quantity"].min()),
    max_value=int(df["Quantity"].max()),
    value=int(df["Quantity"].max()),
    step=1
)

chart_option = st.sidebar.radio(
    "📈 Оберіть графік для перегляду:",
    [
        "Середні продажі за категорією",
        "Boxplot продажів за ринком",
        "Дохід на користувача за країною",
        "Scatterplot ціни замовлення та знижки",
        "Теплова карта кореляцій",
        "Кластеризація покупців (KMeans)"
    ]
)

# Інформаційний блок
st.sidebar.markdown("---")
st.sidebar.markdown(" **Інструкція**: \n Відфільтруйте дані за потрібними параметрами і перегляньте графіки та таблиці на панелі праворуч.")

df_filtered = df[
    (df["Year"] == selected_year) &
    (df["Segment"].isin(selected_segment)) &
    (df["Category"].isin(selected_category)) &
    (df["Sub-Category"].isin(selected_subcategory)) &
    (df["Country"].isin(selected_country)) &
    (df["Market"].isin(selected_market)) &
    (df["Order Priority"] == selected_priority) &
    (df["Ship Mode"] == selected_shipment) &
    (df["Quantity"] <= selected_maxqn)
]

#Регресійна модель
st.sidebar.markdown("Побудова регресії")
numeric_columns = df_filtered.select_dtypes(include=np.number).columns.tolist()

reg_x = st.sidebar.selectbox("Оберіть змінну X", numeric_columns, index=0)
reg_y = st.sidebar.selectbox("Оберіть змінну Y", numeric_columns, index=1)
show_regression = st.sidebar.checkbox("Показати регресійну модель")

st.title("📊 Дашборд")
st.subheader(f"Відфільтровано {df_filtered.shape[0]} замовлень")

#Завантаження csv
csv = df_filtered.to_csv(index=False).encode("utf-8")
st.download_button(
    label="Завантажити CSV ⬇",
    data=csv,
    file_name="filtered_companies.csv",
    mime="text/csv"
)

# Таблиця результатів
st.subheader("Оберіть, які стовпці таблиці відображати")

all_columns = df_filtered.columns.tolist()
default_columns = ["Order ID", "Segment", "Country", "Category", "Product Name", "Sales", "Profit"]

selected_columns = st.multiselect(
    "Оберіть стовпці для перегляду",
    options=all_columns,
    default=[col for col in default_columns if col in all_columns]
)

if selected_columns:
    st.dataframe(df_filtered[selected_columns])
else:
    st.info("Оберіть хоча б один стовпець, щоб відобразити таблицю.")

# Відображення обраного графіка

if chart_option == "Середні продажі за категорією":
    st.subheader("📊 Середні продажі за категорією")
    fig, ax = plt.subplots(figsize=(10, 5))
    sns.barplot(
        data=df_filtered,
        x="Category",
        y="Sales",
        estimator="mean",
        ax=ax
    )
    ax.set_title("Середні продажі за категоріями")
    st.pyplot(fig)


elif chart_option == "Boxplot продажів за ринком":
    st.subheader("📊 Boxplot продажів за ринком")
    fig, ax = plt.subplots(figsize=(10, 5))
    sns.boxplot(data=df_filtered, x="Market", y="Sales", ax=ax)
    ax.set_title("Розподіл прибутку по галузях")
    st.pyplot(fig)

elif chart_option == "Scatter: Ціна замовлення vs Знижка":
    st.subheader("📊 Scatter: Ціна замовлення vs Знижка")
    chart = alt.Chart(df_filtered).mark_circle(size=60).encode(
        x="Sales:Q",
        y="Discount:Q",
        color="Ship Mode:N",
    ).interactive().properties(title="Ціна vs Знижка")
    st.altair_chart(chart, use_container_width=True)

elif chart_option == "Дохід на користувача за категорією товару":
    st.subheader("📊 Дохід на користувача за категорією товару")
    fig, ax = plt.subplots(figsize=(10, 5))
    sns.barplot(
        data=df_filtered,
        x="Category",
        y="Profit",
        estimator="mean",
        ax=ax
    )
    ax.set_title("Середній дохід")
    st.pyplot(fig)

elif chart_option == "Теплова карта кореляцій":
    st.subheader("📊 Теплова карта кореляцій")
    numeric_cols = df_filtered.select_dtypes(include=[np.number])
    corr = numeric_cols.corr()
    fig, ax = plt.subplots(figsize=(10, 6))
    sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f", ax=ax)
    ax.set_title("Кореляційна матриця числових показників")
    st.pyplot(fig)

elif chart_option == "Кластеризація користувачів (KMeans)":
    st.subheader("📊 Кластеризація користувачів на основі вартості замовлень, кількості товарів та прибутку")
    cluster_data = df_filtered[["Sales", "Profit", "Quantity"]].dropna().copy()

    if cluster_data.shape[0] >= 3:
        kmeans = KMeans(n_clusters=3, random_state=0)
        cluster_data["Cluster"] = kmeans.fit_predict(cluster_data)

        chart = alt.Chart(cluster_data).mark_circle(size=60).encode(
            x="Sales:Q",
            y="Profit:Q",
            color="Cluster:N",
            tooltip=["Sales", "Profit", "Cluster"]
        ).interactive().properties(title="Кластеризація за ціною та прибутком")
        st.altair_chart(chart, use_container_width=True)
    else:
        st.warning("Недостатньо даних для кластеризації (потрібно ≥ 3 рядки).")

# Побудова регресійної моделі
if show_regression:
    st.subheader(f"📈 Лінійна регресія: {reg_y} ~ {reg_x}")

    df_reg = df_filtered[[reg_x, reg_y]].dropna()

    if df_reg.shape[0] >= 2:
        model = LinearRegression()
        model.fit(df_reg[[reg_x]], df_reg[reg_y])
        y_pred = model.predict(df_reg[[reg_x]])

        coef = model.coef_[0]
        intercept = model.intercept_
        r2 = model.score(df_reg[[reg_x]], df_reg[reg_y])

        st.markdown(f"**Коефіцієнт нахилу (β):** {coef:.4f}")
        st.markdown(f"**Зсув (intercept):** {intercept:.4f}")
        st.markdown(f"**R²:** {r2:.4f}")

        fig, ax = plt.subplots(figsize=(8, 5))
        sns.scatterplot(data=df_reg, x=reg_x, y=reg_y, ax=ax)
        sns.lineplot(x=df_reg[reg_x], y=y_pred, color='red', ax=ax)
        ax.set_title(f"Регресія {reg_y} ~ {reg_x}")
        st.pyplot(fig)
    else:
        st.warning("Недостатньо даних для побудови регресії.")

